version: '3.8'

services:
  calmative-database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: calmative-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=CalmativePass123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - calmative_data:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'CalmativePass123!' -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
      
  smtp:
    image: rnwood/smtp4dev
    ports:
      - "3000:80"   # Web UI 
      - "2525:25"   # SMTP

volumes:
  calmative_data:
    driver: local 